name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '* * * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: "True"
          SHOW_PROJECTS: "False"
          SHOW_UPDATED_DATE: "True"
          SHOW_LINES_OF_CODE: "False"
          SHOW_PROFILE_VIEWS: "False"
          COMMIT_BY_ME: "True"
          COMMIT_MESSAGE: "🏷️"
          SHOW_DAYS_OF_WEEK: "False"

